version: "3.3"
services:
  hand_tracker:
    container_name: hand_tracker
      #user: root:112409
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - CAMERA_IP=${CAMERA_IP}
      - CAMERA_USER=${CAMERA_USER}
      - CAMERA_PW=${CAMERA_PW}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PW=${MQTT_PW}
      - MQTT_BROKER_IP=${MQTT_BROKER_IP}
    command: python3 read_stream.py
