version: "3.3"
services:
  hand_tracker:
    container_name: hand_tracker
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    build:
      context: .
      dockerfile: Dockerfile
      args:
          XAUTH_TOKEN: ${XAUTH_DOCKER_TOKEN}
    sysctls:
      net.ipv4.ip_local_port_range: "40000 40010"
      #network_mode: host
    ports:
      - "8501:8501"
    devices:
      - /dev/video0:/dev/video0
    environment:
      - CAMERA_IP=${CAMERA_IP}
      - CAMERA_USER=${CAMERA_USER}
      - CAMERA_PW=${CAMERA_PW}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PW=${MQTT_PW}
      - MQTT_BROKER_IP=${MQTT_BROKER_IP}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - DISPLAY=${DISPLAY}
        #command: python3 -u read_stream.py --debug
    command: streamlit run test.py --server.port=8501 --server.address=0.0.0.0
