version: "3.3"
services:
  hand_tracker:
    container_name: hand_tracker
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
      args:
          XAUTH_TOKEN: ${XAUTH_DOCKER_TOKEN}
    network_mode: host
    environment:
      - CAMERA_IP=${CAMERA_IP}
      - CAMERA_USER=${CAMERA_USER}
      - CAMERA_PW=${CAMERA_PW}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PW=${MQTT_PW}
      - MQTT_BROKER_IP=${MQTT_BROKER_IP}
      - MQTT_TOPIC=${MQTT_TOPIC}
    command: python3 -u read_stream.py --prod
